apiVersion: v1
kind: Secret
metadata:
  name: clair
data:
  # The preshared key must be base64-encoded twice! It gets decoded once when
  # rendering the k8s Secret into the process environment (as usual), but Clair
  # sneakily Base64-decodes a second time, without telling us about it in the
  # documentation (as of the time of this writing).
  auth_preshared_key: {{ b64enc .Values.clair.auth.preshared_key | b64enc }}
  postgres_password: {{ b64enc .Values.postgresql.postgresPassword }}
  notification_secret: {{ b64enc .Values.clair.auth.notification_secret }}
