{{- range $component := list "indexer" "matcher" "notifier" }}
---
apiVersion: v1
kind: Service

metadata:
  name: clair-{{ $component }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/targets: "infra-frontend"

spec:
  selector:
    name: clair-{{ $component }}
  ports:
    - name: api
      port: 8080
    - name: metrics
      port: 8081
{{- end }}
